version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - aws s3 cp s3://delta-force-api-files/application.yml ./src/main/resources/application.yml
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - mv target/*.war ./delta-force.war
  post_build:
    commands:
      - echo Build completed on `date`
      - unzip delta-force.war -d artifact/
      - mv artifact/WEB-INF WEB-INF
      - pwd
      - ls -al
artifacts:
  files:
    - WEB-INF/**/*
  name: artifact